spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 10

server:
  address: 0.0.0.0
  tomcat:
    max-threads: 200

Djava:
  net:
    preferIPv4Stack: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
#  type-aliases-package: cn.wbnull.springbootdemo.model  #对应实体类路径